"""Metrics table schemas + configuration.

Owns the shared :class:`MetricsConfig` (start/end date, benchmark, risk-free
rate, coverage threshold) plus the ten wide tables produced by
:class:`amfi.metrics.MetricsBuilder`. Table classes are generated by a
factory and exposed as module-level aliases so callers can import them by
name (``MetricsBasicYearlyTable``) or iterate :data:`METRICS_TABLES`.

Every metrics table has a fixed, declared schema:
``sd_id INTEGER PRIMARY KEY, scheme TEXT, <metric>_<period> DOUBLE, ...``
with one column per (metric, period) pair derived from
:meth:`MetricsConfig.periods`. Periods with no data stay NULL after build.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Literal

from ..error import AppConfigError
from ..core.base import DerivedView, Table

Frequency = Literal["yearly", "quarterly", "monthly"]

_FREQUENCIES: tuple[Frequency, ...] = ("yearly", "quarterly", "monthly")

_BASIC_METRICS: tuple[str, ...] = ("r", "cagr", "sr", "vol")
_BENCHMARK_METRICS: tuple[str, ...] = (
    "beta",
    "alpha",
    "r_sq",
    "ir",
    "m2",
)
_PERFORMANCE_METRICS: tuple[str, ...] = ("sharpe", "sortino")
_RISK_METRICS: tuple[str, ...] = (
    "md",
    "calmar",
    "var95",
    "var99",
    "cvar95",
    "cvar99",
    "ui",
)


# --------------------------------------------------------------- config + helpers


def all_periods(freq: Frequency, start: date, end: date) -> list[str]:
    """Deterministic period keys for every ``freq`` slot in ``[start, end]``.

    Ordered oldest-first. Quarterly/monthly expand to every quarter/month in
    each year of the range; periods outside the strict start/end day land as
    NULL at build time rather than being excluded from the schema.
    """
    years = range(start.year, end.year + 1)
    if freq == "yearly":
        return [str(y) for y in years]
    if freq == "quarterly":
        return [f"{y}_{q}" for y in years for q in range(1, 5)]
    return [f"{y}_{m:02d}" for y in years for m in range(1, 13)]


def period_order(freq: Frequency, periods: list[str]) -> list[str]:
    """Sort ``periods`` latest-first (matches the notebook layout convention)."""
    del freq  # key is purely numeric; kept for signature symmetry

    def key(p: str) -> tuple[int, ...]:
        return tuple(int(x) for x in p.split("_"))

    return sorted(set(periods), key=key, reverse=True)


def metrics_columns(metrics: tuple[str, ...], periods: list[str]) -> list[str]:
    """Flattened ``<metric>_<period>`` column names (grouped by metric)."""
    return [f"{m}_{p}" for m in metrics for p in periods]


@dataclass(frozen=True)
class MetricsConfig:
    """Shared metrics configuration.

    Lives in the data layer because both the table schema (column generation)
    and the runtime builder read from it; moving it here keeps the data layer
    self-contained and avoids a circular import.

    Attributes:
        risk_free_rate: Annual risk-free rate (decimal).
        trading_days: Trading-day count per year used for annualisation.
        start_date: Earliest date included in the metrics computation.
        end_date: Latest date included; defaults to ``date.today()``.
        coverage_threshold: Minimum fraction of the benchmark's trading-day
            count required per (sd_id, period) for quarterly/monthly metrics.
    """

    risk_free_rate: float = 0.07
    trading_days: int = 252
    start_date: date = field(default_factory=lambda: date(2015, 1, 1))
    end_date: date = field(default_factory=date.today)
    coverage_threshold: float = 0.9

    def periods(self, freq: Frequency) -> list[str]:
        """Return the full period list for ``freq`` in calendar order."""
        return all_periods(freq, self.start_date, self.end_date)


# ------------------------------------------------------------- table factory


def _class_name_from(table_name: str) -> str:
    """``"metrics_basic_yearly"`` -> ``"MetricsBasicYearlyTable"``."""
    return "".join(part.capitalize() for part in table_name.split("_")) + "Table"


def _make_metrics_table(
    table_name: str,
    freq: Frequency,
    metrics: tuple[str, ...],
) -> type[Table]:
    """Generate a :class:`Table` subclass for one metrics table.

    The produced class has ``name()`` / ``create_sql()`` classmethods; the
    DDL column list is derived at call time from a default
    :class:`MetricsConfig` so the schema tracks the current year range
    without requiring callers to thread a config through.
    """

    class _MetricsTable(Table):
        @classmethod
        def name(cls) -> str:
            return table_name

        @classmethod
        def frequency(cls) -> Frequency:
            return freq

        @classmethod
        def metric_names(cls) -> tuple[str, ...]:
            return metrics

        @classmethod
        def create_sql(cls, if_not_exists: bool = True, replace: bool = False) -> str:
            if if_not_exists and replace:
                raise AppConfigError(
                    "if_not_exists and replace",
                    "BOTH_CANNOT_BE_TRUE",
                    (if_not_exists, replace),
                )
            if replace:
                prefix = "OR REPLACE TABLE"
            elif if_not_exists:
                prefix = "TABLE IF NOT EXISTS"
            else:
                prefix = "TABLE"

            periods = period_order(freq, MetricsConfig().periods(freq))
            metric_cols = ",\n    ".join(
                f"{c} DOUBLE" for c in metrics_columns(metrics, periods)
            )
            return (
                f"CREATE {prefix} {table_name} (\n"
                f"    sd_id INTEGER PRIMARY KEY,\n"
                f"    scheme TEXT,\n"
                f"    {metric_cols}\n"
                f")"
            )

    _MetricsTable.__name__ = _class_name_from(table_name)
    _MetricsTable.__qualname__ = _MetricsTable.__name__
    return _MetricsTable


# --------------------------------------------------------------- class aliases

MetricsBasicYearlyTable = _make_metrics_table(
    "metrics_basic_yearly", "yearly", _BASIC_METRICS
)
MetricsBasicQuarterlyTable = _make_metrics_table(
    "metrics_basic_quarterly", "quarterly", _BASIC_METRICS
)
MetricsBasicMonthlyTable = _make_metrics_table(
    "metrics_basic_monthly", "monthly", _BASIC_METRICS
)
MetricsRiskYearlyTable = _make_metrics_table(
    "metrics_risk_yearly", "yearly", _RISK_METRICS
)
MetricsRiskQuarterlyTable = _make_metrics_table(
    "metrics_risk_quarterly", "quarterly", _RISK_METRICS
)
MetricsRiskMonthlyTable = _make_metrics_table(
    "metrics_risk_monthly", "monthly", _RISK_METRICS
)
MetricsBenchmarkYearlyTable = _make_metrics_table(
    "metrics_benchmark_yearly", "yearly", _BENCHMARK_METRICS
)
MetricsBenchmarkQuarterlyTable = _make_metrics_table(
    "metrics_benchmark_quarterly", "quarterly", _BENCHMARK_METRICS
)
MetricsBenchmarkMonthlyTable = _make_metrics_table(
    "metrics_benchmark_monthly", "monthly", _BENCHMARK_METRICS
)
MetricsPerformanceYearlyTable = _make_metrics_table(
    "metrics_performance_yearly", "yearly", _PERFORMANCE_METRICS
)

METRICS_TABLES: tuple[type[Table], ...] = (
    MetricsBasicYearlyTable,
    MetricsRiskYearlyTable,
    MetricsBenchmarkYearlyTable,
    MetricsBasicQuarterlyTable,
    MetricsRiskQuarterlyTable,
    MetricsBenchmarkQuarterlyTable,
    MetricsBasicMonthlyTable,
    MetricsRiskMonthlyTable,
    MetricsBenchmarkMonthlyTable,
    MetricsPerformanceYearlyTable,
)


# ---------------------------------------------------------- table kind lookup


_BASIC_TABLE_BY_FREQ: dict[Frequency, type[Table]] = {
    "yearly": MetricsBasicYearlyTable,
    "quarterly": MetricsBasicQuarterlyTable,
    "monthly": MetricsBasicMonthlyTable,
}
_RISK_TABLE_BY_FREQ: dict[Frequency, type[Table]] = {
    "yearly": MetricsRiskYearlyTable,
    "quarterly": MetricsRiskQuarterlyTable,
    "monthly": MetricsRiskMonthlyTable,
}
_BENCHMARK_TABLE_BY_FREQ: dict[Frequency, type[Table]] = {
    "yearly": MetricsBenchmarkYearlyTable,
    "quarterly": MetricsBenchmarkQuarterlyTable,
    "monthly": MetricsBenchmarkMonthlyTable,
}


def basic_table(freq: Frequency) -> type[Table]:
    """Return the ``metrics_basic_*`` class for ``freq``."""
    return _BASIC_TABLE_BY_FREQ[freq]


def risk_table(freq: Frequency) -> type[Table]:
    """Return the ``metrics_risk_*`` class for ``freq``."""
    return _RISK_TABLE_BY_FREQ[freq]


def benchmark_table(freq: Frequency) -> type[Table]:
    """Return the ``metrics_benchmark_*`` class for ``freq``."""
    return _BENCHMARK_TABLE_BY_FREQ[freq]


# ------------------------------------------------------ per-period views


def _period_view_class_name(period: str) -> str:
    """``"2026"`` -> ``"Metrics2026View"``; ``"2026_03"`` -> ``"Metrics202603View"``."""
    return "Metrics" + period.replace("_", "") + "View"


def _freq_of_period(period: str) -> Frequency:
    """Infer the frequency from a period key's shape."""
    parts = period.split("_")
    if len(parts) == 1:
        return "yearly"
    # Monthly periods use zero-padded two-digit month (len == 2); quarterly
    # uses a single digit.
    return "monthly" if len(parts[1]) == 2 else "quarterly"


def _make_period_view(period: str) -> type[DerivedView]:
    """Generate a :class:`DerivedView` for a single period.

    The view selects ``sd_id, scheme`` from :data:`plans` (via
    :class:`amfi.data.derived.PlansView`) and ``LEFT JOIN``s
    ``metrics_basic_<freq>``, ``metrics_risk_<freq>``,
    ``metrics_benchmark_<freq>`` (plus ``metrics_performance_yearly`` when
    yearly), renaming ``<metric>_<period>`` columns to the bare metric name.
    All referenced names come from class ``name()`` methods; no literals.
    """
    from ..derived import PlansView

    freq = _freq_of_period(period)
    groups: list[tuple[type[Table], tuple[str, ...], str]] = [
        (basic_table(freq), _BASIC_METRICS, "b"),
        (risk_table(freq), _RISK_METRICS, "r"),
        (benchmark_table(freq), _BENCHMARK_METRICS, "bm"),
    ]
    if freq == "yearly":
        groups.append((MetricsPerformanceYearlyTable, _PERFORMANCE_METRICS, "pf"))

    view_name = f"metrics_{period}"
    plans_alias = "p"

    class _PeriodView(DerivedView):
        @classmethod
        def name(cls) -> str:
            return view_name

        @classmethod
        def select_sql(cls) -> str:
            select_cols = [
                f"{plans_alias}.sd_id",
                f"{plans_alias}.scheme",
            ]
            joins: list[str] = []
            for tbl, metrics, alias in groups:
                joins.append(
                    f"LEFT JOIN {tbl.name()} {alias} "
                    f"ON {alias}.sd_id = {plans_alias}.sd_id"
                )
                for m in metrics:
                    select_cols.append(f"{alias}.{m}_{period} AS {m}_{period}")
            return (
                f"SELECT {', '.join(select_cols)}\n"
                f"FROM {PlansView.name()} {plans_alias}\n" + "\n".join(joins)
            )

    _PeriodView.__name__ = _period_view_class_name(period)
    _PeriodView.__qualname__ = _PeriodView.__name__
    return _PeriodView


def _all_period_view_classes() -> tuple[type[DerivedView], ...]:
    """Build one :class:`DerivedView` per (freq, period) in default config."""
    cfg = MetricsConfig()
    seen: dict[str, type[DerivedView]] = {}
    for freq in _FREQUENCIES:
        for period in cfg.periods(freq):
            if period in seen:
                continue
            seen[period] = _make_period_view(period)
    return tuple(seen.values())


METRICS_PERIOD_VIEWS: tuple[type[DerivedView], ...] = _all_period_view_classes()


__all__ = [
    "Frequency",
    "METRICS_PERIOD_VIEWS",
    "METRICS_TABLES",
    "MetricsBasicMonthlyTable",
    "MetricsBasicQuarterlyTable",
    "MetricsBasicYearlyTable",
    "MetricsBenchmarkMonthlyTable",
    "MetricsBenchmarkQuarterlyTable",
    "MetricsBenchmarkYearlyTable",
    "MetricsConfig",
    "MetricsPerformanceYearlyTable",
    "MetricsRiskMonthlyTable",
    "MetricsRiskQuarterlyTable",
    "MetricsRiskYearlyTable",
    "all_periods",
    "basic_table",
    "benchmark_table",
    "metrics_columns",
    "period_order",
    "risk_table",
]
